In [2]:
install pytorch as shown on the official site: https://pytorch.org

SyntaxError: ignored

In [3]:
import torch

In [4]:
torch.zeros([3, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones([3, 4, 2])

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [6]:
torch.Tensor([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [7]:
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

In [8]:
x.size()

torch.Size([3, 4])

In [9]:
x.shape # .shape = .size()

torch.Size([3, 4])

In [10]:
x[0]

tensor([1., 2., 3., 4.])

In [11]:
x[1]

tensor([5., 6., 7., 8.])

In [12]:
x[0, 0]

tensor(1.)

In [13]:
x[:, 0]

tensor([1., 5., 9.])

In [14]:
x + 10 # операцияя выполняется поэлементно

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [15]:
x ** 2 # -||-

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [16]:
y = torch.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [17]:
x + y

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

In [18]:
x * y

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

In [19]:
x / y

tensor([[ 0.0833,  0.1818,  0.3000,  0.4444],
        [ 0.6250,  0.8571,  1.1667,  1.6000],
        [ 2.2500,  3.3333,  5.5000, 12.0000]])

In [20]:
x % y

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [21]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [22]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [23]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [24]:
x > 3 # логические операции то же поэлементно

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [25]:
mask = x > 3

In [26]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [27]:
x[x > 3] # !!!!

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [28]:
y = x
y[0, 0] = 999
print(x)
print(y) # заметим, что y - это ссылка на тензор x 

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [29]:
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

In [30]:
y = x.clone() # тут происходит копирование
y[0, 0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [31]:
x.dtype

torch.float32

In [32]:
x = x.double() # так же можно переводить в float, doudle, int
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [33]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [34]:
x = torch.from_numpy(x) # np.array -> tensor
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [35]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [36]:
x = torch.rand([2000,3000])
# x

In [45]:
torch.cuda.is_available() # Доступна ли видеокарта?

True

In [52]:
# :0 - потому что на нашей машине может быть несколько видеокарт
torch.device('cuda:0') # перевод вычисление на gpu

device(type='cuda', index=0)

In [39]:
torch.device('cpu') # перевод вычислений на cpu

device(type='cpu')

In [40]:
# универсальный код, который переводит torch тензор на ту платформу, 
# которая у нас сейчас в компьютере есть
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [55]:
x_cuda = x.to(device) # переводит тензор на gpu / cpu
x_cuda

tensor([[0.1944, 0.2762, 0.8827,  ..., 0.6739, 0.1252, 0.6239],
        [0.5093, 0.7501, 0.4316,  ..., 0.9427, 0.2247, 0.4028],
        [0.6250, 0.3362, 0.6883,  ..., 0.7629, 0.2085, 0.2841],
        ...,
        [0.4369, 0.2985, 0.4893,  ..., 0.0087, 0.9099, 0.8477],
        [0.5038, 0.1935, 0.9571,  ..., 0.8406, 0.9897, 0.0409],
        [0.4876, 0.0810, 0.5817,  ..., 0.7870, 0.4106, 0.8519]],
       device='cuda:0')

In [42]:
# %time - сколько времени выполняется код
%time y = (x - x + x * 10.0) ** 2

CPU times: user 16.9 ms, sys: 27.3 ms, total: 44.2 ms
Wall time: 47.6 ms


In [43]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 96 µs, sys: 1.75 ms, total: 1.84 ms
Wall time: 19.9 ms
